### ISSUE TITLE
关于android列表的每个item高度问题

### ISSUE THREAD

**Issue by lhh-sofy** [janiokq/react-native-nlist#2]
使用列表时候，每个item是不固定的，没有办法计算到。比如头条的文章列表样式
![wechatimg73](https://user-images.githubusercontent.com/13582183/49067113-12240c00-f25e-11e8-8ec0-9ce9865623be.jpeg)

**Comment by janiokq** [comment]
你只是缺少 计算出  Item 高度 的方法而已

**Comment by lhh-sofy** [comment]
好吧，我尝试一下计算高度。能不能给一张ios上的下拉刷新的样式截图。。

**Comment by janiokq** [comment]
![image](https://user-images.githubusercontent.com/10770735/49068974-156dc680-f263-11e8-863f-1a822f9a48a4.png)
![image](https://user-images.githubusercontent.com/10770735/49068988-23234c00-f263-11e8-94f3-c419611cc8f9.png)

**Comment by lhh-sofy** [comment]
那我能否改动刷新的文字。这个需要在原生中修改么？

**Comment by janiokq** [comment]
这个  可以完全自定义 不过 是 基于 原生的 修改   也可以修改 成 自定义动画

**Comment by lhh-sofy** [comment]
ios应用 。rn版本是0.57.6
你好,我这边每个item都给值了，但是显示都有问题。如图所示
<img width="754" alt="wechat765236641320b68a577f7be153482704" src="https://user-images.githubusercontent.com/13582183/49072068-5fa67600-f26a-11e8-9cb9-206a33384110.png">

**Comment by janiokq** [comment]
<img width="340" alt="image" src="https://user-images.githubusercontent.com/10770735/49082372-8ec9e100-f284-11e8-8a0b-647b5e99be7f.png">

**Comment by janiokq** [comment]
高宽
